name: fanfou

# åŒ—äº¬æ—¶é—´å‘¨ä¸€è‡³å‘¨äº”ä¸‹åˆå››ç‚¹æ‰§è¡Œ
on:
  push:
    branches: [ master ]
  schedule:
#  - cron: "0 8 * * 1-5"
  - cron: "*/60 * * * *"

# é€šçŸ¥
jobs:
  # åŒ…å«ä¸€ä¸ªé€šçŸ¥ä»»åŠ¡
  notification:
    # ä½¿ç”¨æœ€æ–° ubuntu ç³»ç»Ÿ
    runs-on: ubuntu-latest

    # å…·ä½“æ­¥éª¤
    steps:

    # å‘é€é€šçŸ¥
    - name: send notification
      env:
        URL: ${{ secrets.TEHANG_SHENGHUO_ROBOT_WEBHOOK }}
      run: |
        curl --request POST \
        --url $URL \
        --header 'content-type: application/json' \
        --data '{
          "msgtype":"text",
          "mentioned_list":["@all"],
          "text":{"content":"ä»Šæ—¥æ™šé¤æ¨èï¼š

ä¸€ã€‚ç›’é©¬ç»å…¸ğŸ¦›å¥—é¤ï¼š

\- 1 çº¢çƒ§ä¹³é¸½+é…¸å¥¶"}
          }'
